version: '3'
services:
  mongo1:
    image: mongo:4.0.4
    container_name: mongo1
    ports:
      - "30001:27017"
    networks:
      - mongo-cluster
    command: mongod --replSet rs0

  mongo2:
    image: mongo:4.0.4
    container_name: mongo2
    ports:
      - "30002:27017"
    networks:
      - mongo-cluster
    command: mongod --replSet rs0

  mongo3:
    image: mongo:4.0.4
    container_name: mongo3
    ports:
      - "30003:27017"
    networks:
      - mongo-cluster
    command: mongod --replSet rs0

networks:
  mongo-cluster:

