server:
  port: 8184

customer-service:
  customer-topic-name: customer

spring:
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: always
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql